version: 2.1
orbs:
  node: circleci/node@1.1.6

commands:
  dependencies-setup:
    description: "docker setup and cache"
    steps:
    - checkout
    - restore_cache:
          keys:
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
    - run: npm ci
    - run: npx cypress verify
    - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
          - /usr/local/lib/node_modules 
          

jobs:
  build-and-test:
    docker:
    - image: cypress/base:10
    parallelism: 1
    steps:
    - dependencies-setup
    - run: npx cypress run

workflows:
   build-and-test:
      jobs:
      - build-and-test
