version: 2.1
orbs:
  node: circleci/node@1.1.6

commands:
  setup-docker:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
        keys:
          - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - run: npx cypress verify
      - save_cache:
        paths:
          - /usr/local/lib/node_modules 
        key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}

jobs:
  build-and-test:
    parallelism: 1
    steps:
      - setup-docker
      - run: npx cypress run

workflows:
   build-and-test:
      jobs:
        - build-and-test
